# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-10 14:14
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_sites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='host_name',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(255)], verbose_name='Nombre host'),
        ),
        migrations.AlterField(
            model_name='website',
            name='ip_address',
            field=models.GenericIPAddressField(validators=[django.core.validators.validate_ipv46_address, django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(255)], verbose_name='Dirección I.P.'),
        ),
        migrations.AlterField(
            model_name='website',
            name='last_update_host_name',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(255)], verbose_name='Última actualizacion de nombre host '),
        ),
        migrations.AlterField(
            model_name='website',
            name='last_update_ip_address',
            field=models.GenericIPAddressField(validators=[django.core.validators.validate_ipv46_address, django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(255)], verbose_name='Última actualizacion de Dirección I.P.'),
        ),
        migrations.AlterField(
            model_name='website',
            name='last_update_mac_address',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(255)], verbose_name='Última actualizacion de Dirección M.A.C.'),
        ),
        migrations.AlterField(
            model_name='website',
            name='mac_address',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(255)], verbose_name='Dirección M.A.C.'),
        ),
    ]
