# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-10 16:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_sites', '0003_auto_20161210_1119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='website',
            options={'ordering': ('url',), 'verbose_name': 'Web Site', 'verbose_name_plural': 'Web Sites'},
        ),
    ]
