# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-10 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('web_sections', '0001_initial'),
        ('web_sliders', '0001_initial'),
        ('web_slides', '0003_auto_20161210_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='websection',
            name='web_slides',
            field=models.ManyToManyField(through='web_sliders.WebSlider', to='web_slides.WebSlide'),
        ),
    ]
