# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-10 18:31
from __future__ import unicode_literals

from django.db import migrations, models
import infos_systems.validators


class Migration(migrations.Migration):

    dependencies = [
        ('web_headers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webheader',
            name='image_left',
            field=models.ImageField(default='default/No_Avatar_1.png', upload_to='images_web_headers', validators=[infos_systems.validators.valid_extension], verbose_name='Imagen (Izquierdo)'),
        ),
        migrations.AlterField(
            model_name='webheader',
            name='image_right',
            field=models.ImageField(default='default/No_Avatar_1.png', upload_to='images_web_headers', validators=[infos_systems.validators.valid_extension], verbose_name='Imagen (Derecho)'),
        ),
        migrations.AlterField(
            model_name='webheader',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='files_web_headers', verbose_name='Vídeo'),
        ),
    ]
