# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-10 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_sliders', '0002_auto_20161210_1325'),
        ('web_portals', '0001_initial'),
        ('web_headers', '0005_auto_20161210_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='webheader',
            name='web_slider',
            field=models.ManyToManyField(through='web_portals.WebPortal', to='web_sliders.WebSlider'),
        ),
    ]
