# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-10 17:11
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('web_sections', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web_slides', '0003_auto_20161210_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha registro')),
                ('host_name', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(255)], verbose_name='Nombre host')),
                ('ip_address', models.GenericIPAddressField(validators=[django.core.validators.validate_ipv46_address, django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(255)], verbose_name='Dirección I.P.')),
                ('mac_address', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(255)], verbose_name='Dirección M.A.C.')),
                ('last_update_date', models.DateTimeField(auto_now=True, verbose_name='Fecha última actualización')),
                ('last_update_host_name', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(255)], verbose_name='Última actualizacion de nombre host ')),
                ('last_update_ip_address', models.GenericIPAddressField(validators=[django.core.validators.validate_ipv46_address, django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(255)], verbose_name='Última actualizacion de Dirección I.P.')),
                ('last_update_mac_address', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(255)], verbose_name='Última actualizacion de Dirección M.A.C.')),
                ('is_selected', models.BooleanField(choices=[(True, 'Yes'), (False, 'Not')], default=True, verbose_name='¿Es Seleccionado?')),
                ('position', models.SmallIntegerField(default=0, help_text='Ingresar posición de las diapositivas web, rango (1-7) .', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)])),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('last_updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='web_sliders_webslider_related', to=settings.AUTH_USER_MODEL, verbose_name='Última actualización por')),
                ('web_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_sections.WebSection')),
                ('web_slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_slides.WebSlide')),
            ],
            options={
                'verbose_name_plural': 'Web Slider',
                'db_table': 'web_sliders',
                'verbose_name': 'Web Slider',
                'ordering': ('web_section', 'web_slide'),
            },
        ),
    ]
