# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-10 18:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_sliders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webslider',
            name='web_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_sections.WebSection', verbose_name='Sección Web'),
        ),
        migrations.AlterField(
            model_name='webslider',
            name='web_slide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_slides.WebSlide', verbose_name='Diapositiva Web'),
        ),
    ]
