# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-10 16:25
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import infos_systems.validators


class Migration(migrations.Migration):

    dependencies = [
        ('web_slides', '0002_auto_20161210_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webslide',
            name='image',
            field=models.ImageField(default='default/No_Avatar_1.png', upload_to='images_web_slides', validators=[infos_systems.validators.valid_extension], verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='webslide',
            name='slogan',
            field=models.CharField(db_index=True, max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(255)], verbose_name='Slogan'),
        ),
        migrations.AlterField(
            model_name='webslide',
            name='title',
            field=models.CharField(db_index=True, max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(255)], verbose_name='Título'),
        ),
    ]
