# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-10 09:17
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(db_index=True, max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(50)], verbose_name='Nombre de usuario')),
                ('email', models.EmailField(db_index=True, max_length=100, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Correo electrónico')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='¿Super usuario?')),
                ('is_staff', models.BooleanField(default=True, verbose_name='¿Ingresa al staff?')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Activo?')),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha registro')),
                ('host_name', models.CharField(max_length=255, verbose_name='Nombre host')),
                ('ip_address', models.GenericIPAddressField(validators=[django.core.validators.validate_ipv46_address], verbose_name='Dirección I.P.')),
                ('mac_address', models.CharField(max_length=255, verbose_name='Dirección M.A.C.')),
                ('last_update_date', models.DateTimeField(auto_now=True, verbose_name='Fecha última actualización')),
                ('last_update_host_name', models.CharField(max_length=255, verbose_name='Última actualizacion de nombre host ')),
                ('last_update_ip_address', models.GenericIPAddressField(validators=[django.core.validators.validate_ipv46_address], verbose_name='Última actualizacion de Dirección I.P.')),
                ('last_update_mac_address', models.CharField(max_length=255, verbose_name='Última actualizacion de Dirección M.A.C.')),
                ('created_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('last_updated_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auth_users_auth_user_related', to=settings.AUTH_USER_MODEL, verbose_name='Última actualización por')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'auth_users',
                'verbose_name_plural': 'Auth Users',
                'ordering': ('username',),
                'verbose_name': 'Auth User',
            },
        ),
    ]
