# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-13 15:26
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import persons.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha registro')),
                ('host_name', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(255)], verbose_name='Nombre host')),
                ('ip_address', models.GenericIPAddressField(validators=[django.core.validators.validate_ipv46_address, django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(255)], verbose_name='Dirección I.P.')),
                ('mac_address', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(255)], verbose_name='Dirección M.A.C.')),
                ('last_update_date', models.DateTimeField(auto_now=True, verbose_name='Fecha última actualización')),
                ('last_update_host_name', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(255)], verbose_name='Última actualizacion de nombre host ')),
                ('last_update_ip_address', models.GenericIPAddressField(validators=[django.core.validators.validate_ipv46_address, django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(255)], verbose_name='Última actualizacion de Dirección I.P.')),
                ('last_update_mac_address', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(255)], verbose_name='Última actualizacion de Dirección M.A.C.')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Activo?')),
                ('auth_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_user_authuserprofiles_related', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('last_updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_users_profiles_authuserprofile_related', to=settings.AUTH_USER_MODEL, verbose_name='Última actualización por')),
            ],
            options={
                'verbose_name_plural': 'Auth Users Profiles',
                'ordering': ('auth_user',),
                'verbose_name': 'Auth User Profile',
                'db_table': 'auth_user_profile',
            },
            bases=(persons.models.Person, models.Model),
        ),
    ]
