# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-13 15:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_users_profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authuserprofile',
            name='auth_user',
        ),
        migrations.RemoveField(
            model_name='authuserprofile',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='authuserprofile',
            name='last_updated_by',
        ),
        migrations.DeleteModel(
            name='AuthUserProfile',
        ),
    ]
