# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-13 15:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_users_profiles', '0003_authuserprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuserprofile',
            name='blood_group',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auth_users_profiles_authuserprofile_related', to='blood_groups.BloodGroup', verbose_name='Grupo Sanguíneo'),
        ),
        migrations.AlterField(
            model_name='authuserprofile',
            name='gender',
            field=models.BooleanField(choices=[(True, 'Male - Masculino'), (False, 'Female - Femenino')], default=True, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='authuserprofile',
            name='type_person',
            field=models.BooleanField(choices=[(True, 'Natural - Natural'), (False, 'Legal - Jurídica')], default=True),
        ),
    ]
