# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-13 17:36
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bar_code_types', '0001_initial'),
        ('auth_users_profiles', '0005_auto_20170213_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuserprofile',
            name='bar_code_image',
            field=models.ImageField(default='', upload_to='bar_codes', verbose_name='Imagen Código de Barra'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='authuserprofile',
            name='bar_code_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='bar_code_types.BarCodeType', verbose_name='Tipo de Código de Barra'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='authuserprofile',
            name='bar_code_value',
            field=models.CharField(db_index=True, default='123', max_length=255, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(255)], verbose_name='Valor Código de Barra'),
            preserve_default=False,
        ),
    ]
