# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-13 17:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_users_profiles', '0006_auto_20170213_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authuserprofile',
            name='auth_user',
        ),
        migrations.RemoveField(
            model_name='authuserprofile',
            name='bar_code_type',
        ),
        migrations.RemoveField(
            model_name='authuserprofile',
            name='blood_group',
        ),
        migrations.RemoveField(
            model_name='authuserprofile',
            name='civil_state',
        ),
        migrations.RemoveField(
            model_name='authuserprofile',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='authuserprofile',
            name='identification_document',
        ),
        migrations.RemoveField(
            model_name='authuserprofile',
            name='last_updated_by',
        ),
        migrations.DeleteModel(
            name='AuthUserProfile',
        ),
    ]
